### ISSUE TITLE
src/static/json

### ISSUE THREAD

**Issue by hangtiancheng** [Natrium0521/Firefly#12]
你好，可以分享一下如何获取这些 json 文件吗 （src/static/json），我是一名学生，对这个项目很感兴趣，希望可以学习一下，谢谢！

**Comment by Natrium0521** [comment]
https://gitlab.com/Dimbreath/turnbasedgamedata

**Comment by hangtiancheng** [comment]
> https://gitlab.com/Dimbreath/turnbasedgamedata

谢谢🥳
