### ISSUE TITLE
[Feature]希望增加手动抽卡记录补全

### ISSUE THREAD

**Issue by cx-xingchuan** [Natrium0521/Firefly#9]
之前在其他平台查询过，但是这个平台不兼容SRGF标准，故无法导出兼容SRGF标准的json文件，所以希望增加一个手动补全选项，让自己可以手动补全之前的抽卡记录，使其全部在一个工具上面显示

**Comment by Natrium0521** [comment]
手动补全的内容不全且不准，比如三星四星物品不可能全都记住，每条抽卡记录对应的id也不可能完全正确，违背了UIGF/SRGF的[设计初衷](https://uigf.org/zh/goal.html)。
如果有补全的需求可以自行修改导出的SRGF/UIGF文件，文件格式见：[UIGF](https://uigf.org/zh/standards/uigf.html)、[SRGF](https://uigf.org/zh/standards/srgf.html)

**Comment by cx-xingchuan** [comment]
了解了，感谢您的回复
